'''
logo.py: Embedded icon for use in the "About" panel

The rest of this file was generated by using the img2py.py program that
is provided with wxPython 4.0, with the following commands:

  convert -background none -resize x180 ../.graphics/martian-logo.svg martian-logo.png
  img2py -f -i -n MartianLogo martian-logo.png logo.py
  rm martian-logo.png

The only changes to the output were to add the file header and this
explanatory comment.

Authors
-------

Michael Hucka <mhucka@caltech.edu> -- Caltech Library

Copyright
---------

Copyright (c) 2019 by the California Institute of Technology.  This code is
open-source software released under a 3-clause BSD license.  Please see the
file "LICENSE" for more information.
'''

from wx.lib.embeddedimage import PyEmbeddedImage

MartianLogo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAJAAAAC0CAYAAAB7e6WYAAAABGdBTUEAALGPC/xhBQAAAAFz'
    b'UkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAA'
    b'AAZiS0dEAAAAAAAA+UO7fwAAAAlwSFlzAAAASAAAAEgARslrPgAAFopJREFUeNrtnXmQHNV9'
    b'xz+zu7OrY4VWNxZoZYGwEmHAiACWQeEKWE4csAm+g48kdlWcoKKgnJCkUglOJS6TOLFFpRLs'
    b'srFDgrGdALY5DMHBEOEAMkYSt8QlCSTQ6lpdK+0xkz++72l6e6dnenpmtnuW36dqS6vdnZk3'
    b'b379u9+vwTAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzBSJZf2AtKguKq3ac+dW70l'
    b'7bc3rrSlvQCjtXlLaKAqGqcbmO6+ety/04ApQBfQARSAQeAwcADYB+wF+t2/+4GhqBeYyFpp'
    b'wgpQGaHJAXlgMhKOKcAxwDzgeGAB0Ov+PRaYiQRpMjCMBKcf2AG8DmwBtrqvbcAe9zcDwCHg'
    b'CDAyZhETTJg60l7AODIJeDtwFnAO8C5gqtuDLqDTfXUhQesA2t1j293PjkHC9StIIx1x/w4i'
    b'YXkFeBRYAzwH7ASKab/xZjKhNFAZrdMFLEHC8k5gDrAIOAmY34QlHAReAjYhrbQVeAJ4Gmmu'
    b'UUwEbTQhBCgkODnky8wFTgTeA6wEzkhhaX3AT4AHgaeQUO1EGkuLbXEhmkgmLIeiyh7gPOBS'
    b'4ALkJE9NaU0zgQ8AlwAbgR8DdyEtNcQEMG8tr4EC2mcG8m8uR2brHcDb0l5fgAFk2l4Efgbc'
    b'A7xMQIhaURu1pACFTFYnco5/Dfgt4COUnN+ssh74LvC/wAvALv+LVhOiVjZhPiw/Cfgk8D73'
    b'fS3J0YL7Ggl8H8es5CiZzDYksG3EvyCXAtcAZyJBuh+F/iMxH58ZWk4DBbRPJ/JzrkQR1nEo'
    b'6qqFPcDzwAYUMe1EuZ5gDscLlBeaPPKrZqKQ/h3AqSi6q5WdyB96APhX4DX/i1bRRC0jQCGz'
    b'NQM5pp9AZiuu1hkCNqMPbSeKijYBz6LkYB8KxYPkGZtlbgdmoSTkYqRRFgKzkSAvQRntuLwC'
    b'3AzcATyDE9pWEKJWM2E59MEsB/4CfXDVhKeIHNh9wHbgPuBHKDdz2P2+4J4nj4TTZ6unI0EZ'
    b'QH7KQWRqBpD22oWE7y63tuOBFcgP+1X3XD5ZWYmFwJ8jrfotpImGQBdOlgWplQQo59a7ErgO'
    b'+TtxnOUB4H+A/6SU4NuBBCFIN3A6cBHyTWa418sjARtyX88BD6NI6jVKPhSovHEP8EtUFlkB'
    b'fBwJViVt34Yy5Z9CAvs3SNgzT0sIkDNfeWSurgROi/GwPcDjKIG3BkU8u8v83TzgXFSeOBlY'
    b'RmVn/CTk75yGIqhfIIEB1cz63NcLyCzuRJnwZUgrVWKBe4+vA7cWV/W+ktaexyXTPlDA7+lC'
    b'WeUvIw1UTfD7gEeA7yBtcVRwcqu3UFzV67XZPOBC4HOUamOxl4f8qTuAW5B2O5hbvaUY8tfa'
    b'kLBdDnwUCUlXlefdhkz0Hcj0ZtaMtUo/0NuR5jmZ6sIziPyI61EJYW+Zv2lHEdS1yFycjnye'
    b'Wsghh/lK4Ebg3cgMhSkgs/cN5OdsjPG8s1AG+yIyntPKugnzda1lwG+iD70Sr6C8yg+Q6RqB'
    b'0Vev0w6zgA+hSM6rix8ic5RDkdVZyKx5DqCQ/wmkeSajUsnpqM72MeBwcVXvmuBrutc7jPyj'
    b'Q0hQP4w0adQF3AWcjUzZeuRrDZJBMitAbuPb0YezEvkP+QoP8ebkRuAN/8Myqr8NVeI/iDTb'
    b'IVRSuAXVqnJIKIbc77vcz3ah6O0OFHlNQ45uG3K6V7qfP4Z8oVGhuHs/O4F/R9HcdPfeymmt'
    b'HCrDnIO01+3FVb3bs2jGsmzCcsgn+TDyH6KEvYiuzn8D/h59SJXII03Wi7TIVuQrPYmEZtB9'
    b'/xiBcBr5VXchE1REQnA3isbaKDWmTa+yrwXgXuCvUD6qUvZ5KXAVctwz6a9mWYC6KUVE3URv'
    b'4C7gn1CY/ga6+smt3hLleHYh7eE1Sw59qEeQYBTd96+iq/+Ie9wh4E0kYEX3Oofd/3NIW051'
    b'ax2zr4G1eOF7Agn8mgp70Ik00TJgQTMPAyQlkwLkNmouKlVU2rUdwEPI/Dztf1hF1QfzNiAf'
    b'693InMynZFJ2IJ/nMMolvem+B/kxvcDFyNzlQs9dtp4WEup+4HZkFjcS3VOdB34DFYubeqIk'
    b'CVn1gdrQB3Q5inTKUUBm5mbkoBZi+ggHkdYacM8xGzno3gw9iYRlEtI6BfRh70Idjd3IVJ0K'
    b'fBbV4UAaqR+lDCoWRV0qoYgc8/vcc17l1hJmEnL2n0emz2fPM0FWBWguMl3TKB/GFtDmbwD+'
    b'j7H1q0oUkT/zNOpxnolMz3ko6tqDzFanW0ePe8x7UY2rQKnMscj93SDq83kZCWbcD7joHrMG'
    b'uMK9Vvgz8QXc41B0uJGSWU2dTAlQQD0vQWYlKuoaQM7rz3FJwrgRirv6+9CVfzwSINDVP7vC'
    b'QxcRXXE/gkzpeiRgsdbh3vMAEop7kWCeWOH1V6AkY2YEKIs+UA6Zh3OJztjuR7mexyo4y5XY'
    b'iwToWUpOcVJGkHn7b+CZWtfj/nYncCvKXUWxGDgfmJYlPyiLApRHmqGXaA3pczd7E77GEArR'
    b'11E9lK7GbhRRbaI2UxrkiFtHX4W/6UG9R9PqWGvDyZoAtSOTMoNSmB1mO/IZ3iT5B+9bPB5E'
    b'zVz1aKCXUArhdWKar4j1HEQCvY7yEVk78tlmU3vjXNPImgDlUSh9TIW/eQm1TOxJmpkNPO6X'
    b'6NjNJkohely8M/5z9xx7G7Cex5FvFxXSt8fYn3ElawLUiUzXzAp/04e69pKaiyAFFMndSPUi'
    b'Z5gB4HvAfyGfrBGh9WYkzFGa1e/PjAa8VkPIVBRGvA06gMzYUKxnrM4O5ACfiKKgxTEe04+O'
    b'MN+L0gGNaIYvIp+uj2hTmI+xP+NK1gQoj/pleir8zSDSPkn9DWBUGD2IyhZ3UypFzCG6jWI/'
    b'8lO+j0xgI/t1hhjbKRmkEwUYJkAR5FHtp1JDegFX72ogBZSQLCAhuhglEYNC5Iu265DTfCfS'
    b'RI3GHzGK2p/51Naw31Sy5gO1Uyp0hgkWMIuNam1wz+MLqOuBr6PK/nOhP92P6lY3oar8bmAk'
    b'YR6q0lqGidZCbRX2JxWypoFylMarlMOPVGn8CytD7X0bf+riXGTSBlGz2t1IU+30j2kCI5Rq'
    b'cOELvI3S0KtMMG4LiZk99XWfcpqxiHyE4RqeL8n6RpAm2oj8nIXIud1KaBJZk9bgp6GNlNkH'
    b'38vdHue1x6MBLTOS7Kg2scKbsWYfAR5B0d4BlCAcz0kacV4rM0egmyZAFa6QySgRFp5JOBlV'
    b'nOdRPgPtr75lwOepMwqL8xbcvwVKjWfj0RW42O1J1Gt1IdM6QvmZjf1IUxbCn0EzNFJDN6SM'
    b'0HSgfpYplELk2SgUDc4l9DMJuxk93HLU0xMwYROcHArZw6kE7+wfRqmMvShvFJzZ+BrqzOx3'
    b'f3MQ+XSjisbO56tbqJppwnyD1ruAX3df09xrBucRdjJ2JmGUBsq7r0z2BzeQKBPmg4xOShfj'
    b'QnTuLDiv0ftQz6BTuY+i4nMjsvdjFlTfOx2rdeah9sszUUJuIaoin9ToxRtV2Y3SES+hjPuL'
    b'6KDliwSCgXq0UCIB8qovIDx5dNZqETp+cylqE80neX6jabyA+o7WIiHahlIGiaeB1GvC/GmE'
    b'49A5qz9EDmCciRTG+HMCsAqZu4eB1aiWd4CEUWbNGqjMnJ7z0fnyFcQbemBkAz8/4EHkJ8U9'
    b'1TKKmgQoIDw5VL0+F7gMOcgza3kuIxMUKfVE3YNaWw74X8YRpCRmpgMVGj8N/K77PjO1GaNm'
    b'/Hi+s9CgibWUDllWJZYAhczWIuDP0DGYBWSvIGvEx6dGZiIB+lvgX1CjXCwBqvXDX4Jm3FyO'
    b'HDITnonDdEoT1S4BJsept1XVQO5JcihDfCmKtNKa/G40nwuRYtgCbCqu6h2CaH8orgaZgvI6'
    b'FyCfx0L0icsUNBXkcqIPOR4ljgC1oy7B96OyRKYnZhkNYS6Krk9DtczIaD1SgIqrer35molK'
    b'E8vJ1r0njOYxBXU9LEdaKLL/KI4pOhk5znPTflfGuJJDLst2dOigbBdER5Un6EDR1tnU5zgf'
    b'QEdgnsedYnBMQ5HdSrLTKF5Ax3zWMXra2SS3FxejVpSs8Chqs32DUo+UPx5+HlIASfDJ4mWo'
    b'f+tozSxINQGagXI9c0kesm9Dpze/geb5BAWoG+UfiiirnfYHsxvNB/o2Su8H7zLYCZyCWiJW'
    b'Eu/8WDM5hIZD/Aea7bg58Lsc6oB4A40IXEKywvZUVOecj3rEx5zerSQU7UgCFyR8g7799Pto'
    b'nO4jBNLkgU14FPiC24ijwylTYASNaFmFTl3sCv1+CNWLvohG6u1Lca0FJDxXoxMkr4d+7+cO'
    b'3YjmTfuJ+kmYhqKyshaikgbqQAOXTkj4wvvQlfEjlFMAxozcLSAhOoROPByLck3jfXBuEI17'
    b'uQ010x+dsxhYq+8G7EPn17+JQt2F47xWkEa/DY2DOarRQxNhh1DH4lq31g+RrNjd4x63Fg20'
    b'GEU1DbTYbVCSvqH9SIDWhd9gxP+fQrOam3FYrxrDSCgeosxs6TL/34zOxG9LYa2gAug9uPNj'
    b'4bNpof/vQocgX0j4WtORH1X2oq4kQG3IfL2NZAI0jFTn3kqH7wK/60c9vWkM1C6gaKOPCocW'
    b'A2s9RGlweBr4PuiRShVz97shtK97E77WVOTKdJf7ZSUT1oakbhLJKCCHs5Z5gf5AXRr4oZtx'
    b'13qQ9Br8ff9zLWtNOoyiA3WblpWDShrI30erHkcxieZKq2G+lRr1a11rPe+tGPgaQ0eVB+5G'
    b'WqGb2mlzj2svruot61fAqFYRfy4+rQq/b8MdjjruElhrG8qNpNXzPQmdo4sz8jdHfefph1E6'
    b'o+wArkof1giy89tjLLIceeSAx42oetzfdyZ8o/Xg758RdagxzFR0H420uhLmIv80TiWhi9o+'
    b'hzAHUAP+/nK/rCZAm1AaO4kATUe3fjzb/yBcTwn9/wzUi5LG7Js8uuvz0TvoVFnriejugklz'
    b'ZPWyHM2VnuJrlsH1hX42G3WOvjPRKym4eRolEsdQSYJHUOiX9K553cBvo9zBVhT67ne5H48f'
    b'V7IAVX8va9we10QeHQ4YROWW54H+4qresJM8FeWq3ofqg0kDjHpZhjTLUyg/sxsYDAl5FzqX'
    b'dxG6MJMWwvtRr3RZAaqmgV5GZqweR/oK4KuoLjOT0efMZ6BbGv0jut9W2pwD/DMS5GNDa52G'
    b'EmrXowxw2n3gi4GvAZ9BJqojsNZJqHxxNfB3SJCSsg8dTiybn6vmRPejXM52t6FJGsl60NT5'
    b'q1CW2Yfq/nZOC4D3kI0ux6moyfwP0EmTfYG1TnJ7cDbZ6EzoQv3pH0PmaQ+ltEInMl3LkG+X'
    b'lP3IerxBRBqgmgANIwdqDfIPehIuZDK640wrkEM+xvK0FxKTU9xXM3gBjR6OrPvFCZmfRXWX'
    b'egZpG62Fnwf5U1SjjExCRgpQIG2/D03sWoPMmTHxOYhabx5DJmyknqb6ERRJ/Rj1ymTmXlVG'
    b'0+hDBdj1VDlkWFWAnOQdRl16DyIt9FYY8vRW5QASnB8Cr1abQhu3bOBt4h3AP5BOy4UxPtwN'
    b'3EBMn7fWsHwLksz56JhP0n5bI3vsRRbmFtQlGmsWd5LpHG0onP88cCWqH3Vj58ValQEkPL9A'
    b'7bpPEtFUV44kicGCe8FvohrJR1EZYF7aO2HUzBDyd+5EfeAvU+MI4XoHTE1HpyrOQYnCc9Le'
    b'ESM221Fb7MPIZB293VXTBkx5ysxInI8Kp59B9a05ZOiOMsZRBpHg9KOzZF9HieKjvT61zkls'
    b'1JCEHShb/SCqJX0E+ACji5Gt1PE3UQh3E76Czuetcd/3U2cPejPG/M5C0dlS5BctQVXspeO3'
    b'b4ZjJzoVswFllLciJ3kraY75jSJiZvQpqBp/BmqJ8JPr/fT6KajY2oUNrKqVQWR+BihNpT9E'
    b'aTL9i8i/WYsc5DHaJsuT6kFXwMPI3uZRH/E8dHuDXtQWuhD5ULMo9e6GBamD6Ls4BzczjSNB'
    b'SWlDF1Oli2aY8qWEIUq3OvANe6+ipr0tKAm4GwmXvz1EU27Q0jS/pMJ4tEmU7pvRTUkL+fuE'
    b'tQXW5e33CuCP3N9FcRsKR2MPiEyRNjS5/1oq9xY9hG5wd5DRn5W/a6PXQAcp3V3Ia6ExAtOM'
    b'm600TQOFFxsQqMPua1fMpzoLmbgoYT+ENvoWFJa2Cscj4bmU6NtA5FGC9iESlI/G435hmYqM'
    b'QlprEmrbvB5tcjlhP4icxGuQc1hxnl9WcO+zHaU6rkZzJ3sYa878idk/QeNx9lLHbQmaQZad'
    b'1lNR4fZ8ojXlT9DI4Wdo3G3Ax4sRpIW/hcbr7ivzN22ojfYv0VzutJr4I8mMBgpNwb8A1dk+'
    b'TvlzYkOoP+lmZLYKkJ2rssb3C+pt/hw6gBA1d2gtGuXyPdSvQxbec+oCFNrIyShv9AUkPOXY'
    b'j/Iaf0rpVt2pb2Sd79/PIbgO+ASlEyFhNiON+wCKcFM3Z1kyYTkkPDegkcJR/AxFL+uYOD3a'
    b'vkC9GvgK0TeGmw98CWX6K05PHS9SXUBI+1wIfBbV1KKO+NyGoq37KTMEqlUJ7cNidJL0k8i0'
    b'leNxtxffJnDgL429SEWAykRbp6JI5NMRD9mHNM5fIw2Uuupu8p7MQabqgyjZWo6NqH/np+jc'
    b'FmnsSdomrANdcV9EDmQ5htHpgGvcv1lPEjaCPciU30TEdFSknW6gpLFT+SzHXQOFrrTz0VDL'
    b'C4ke8/td4DtI8xw5uvAJpH0q7M9JwO8Af4ympZbjCWTObiIwQWO89ieNUgYoND8Lmazfj/ib'
    b'PSjK+goauTuuG5Mmob2bjaLS9xPd0fAUmi9wH0o8liXz940PbYC/n6q/VbdXsTl0NX0JDe2O'
    b'GlKwHkVbG5AaHyQwBniiClJo4FYepTZmoVrg1REPG0a5oetQXswfu/LH031BteEpj2ZW4/2c'
    b'6RWonWNe4PUmI8e50oSLhZRmHG9AWuh50htsOd4ch/ZtBaqbLUUCUe6i70C5o2tR/sz7TP3o'
    b'fPsDSEvtbfQimyVAk5GTdwWaT3Matd/KoAdlpA+jnqIFwA+QZtpf43O1Ep1IGC5DAy3OpDSe'
    b'pVIAkUMX5amBnw2jzsNe4HbUidhPA/NnzRKgY5F5+j30wddjKichATwROdH+5OREjcZ60GiZ'
    b'TwGnM3rvat1HH+WegCxCP4pkj9T4PJE0K/Rbiq6gOYzu70mKv2PiJejkR9rph2ZyPMr/LKJx'
    b'e9eOZjC9lwYPxmrWB9GD1GYjp5jmUCo/C8OdmskUmjPAcw7yqxp6ALRZAtSP2iob2WJRRBnX'
    b'nfU+UcYZQC2qjQ4WdqH9a2hra7ME6Dl0hn4XjfNV/ISQR5g4RdRyvIaGWLxK4/augHJq99FA'
    b'/wea50RvQx/2DJRlPgU1zCdhEIWij6A7/7zIxHWgQQnUh1Hupw+dZpmV8LkKSBAfRRHsBhrc'
    b'eNcsARpAOZtbkTAtJ9mQziLSYuuQQD5LdKvDRGEQfei3I5OzGUWySZxfP2H1fhS57m70YpuZ'
    b'SPQDOregWk1S562ArpojtF7balKKyJTdiTLL7SSLxoo0ee/SqoUlX/AELWEEsb0zDMMwDMMw'
    b'DMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMw'
    b'DMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMYb/4fXNocOqGW2e0AAAAldEVYdGRhdGU6'
    b'Y3JlYXRlADIwMTktMDYtMDVUMTA6NTg6MzYtMDc6MDBqyS+3AAAAJXRFWHRkYXRlOm1vZGlm'
    b'eQAyMDE5LTA2LTA1VDEwOjU4OjM2LTA3OjAwG5SXCwAAAABJRU5ErkJggg==')
getMartianLogoData = MartianLogo.GetData
getMartianLogoImage = MartianLogo.GetImage
getMartianLogoBitmap = MartianLogo.GetBitmap
getMartianLogoIcon = MartianLogo.GetIcon
